server:
  port: 8080
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: api-catalog
          uri: lb://catalog-service
          predicates:
            - Path=/api/v1/catalog/**
        - id: api-movie
          uri: lb://movie-service
          predicates:
            - Path=/api/v1/movies/**
        - id: api-serie
          uri: lb://serie-service
          predicates:
            - Path=/api/v1/series/**
            
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
     
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
